first
websolcr/rn-constructions pull request #11
Opened 2022-02-13 16:38 UTC by Kushan1994

2022-02-13 18:43 UTC, sureshhemal requested changes

2022-02-13 18:43 UTC, sureshhemal commented on routes/web.php
> +});
create separate controller. 

`HomePageController.php` and call a method named '__invoke'

2022-02-13 19:02 UTC, sureshhemal requested changes

2022-02-13 19:02 UTC, sureshhemal commented on routes/web.php
> +});
`Route::get('/home', HomePageController)->name('home');`

2022-02-13 19:02 UTC, sureshhemal commented on app/Http/Controllers/HomePageController.php
> +
`return Inertia::render('test');`

2022-02-13 20:06 UTC, sureshhemal requested changes

2022-02-14 07:23 UTC, sureshhemal requested changes

2022-02-14 07:23 UTC, sureshhemal commented on resources/js/Components/LayoutComponents/Footer.vue
> +<script setup></script>
remove unnecessary script tags from components

2022-02-14 07:23 UTC, sureshhemal commented on resources/js/Components/LayoutComponents/LineFooter.vue
> +<script setup></script>
remove

2022-02-14 07:23 UTC, sureshhemal commented on resources/js/Components/LayoutComponents/Navbar.vue
> +<script setup></script>
remove script tag

2022-02-14 07:23 UTC, sureshhemal commented on resources/js/Components/LayoutComponents/Topbar.vue
> +<script setup></script>
remove

2022-02-14 07:23 UTC, sureshhemal commented on resources/js/Layouts/Frontend.vue
> +        <Footer />
As we discussed there is two footers. Which one is this one and where the other? One should be fixed on bottom of the page

2022-02-14 07:29 UTC, Kushan1994 commented on resources/js/Layouts/Frontend.vue
> +        <Footer />
yes. i did it. inside the line footer components

2022-02-14 07:33 UTC, sureshhemal approved these changes

2022-02-14 07:34 UTC, merged