create-heading
websolcr/rn-constructions pull request #34
Opened 2022-02-20 12:53 UTC by Kushan1994

2022-02-22 13:11 UTC, sureshhemal requested changes

2022-02-22 13:11 UTC, sureshhemal commented on resources/js/Components/ProjectFrontend/Completed/Complete.vue
> +<script setup>
File name not clear

2022-02-22 13:11 UTC, sureshhemal commented on resources/js/Components/ProjectFrontend/Completed/ContentFrontend.vue
> +<script setup></script>
file name not clear

2022-02-22 13:11 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +import Complete from "@/Components/ProjectFrontend/Completed/Complete";
filename not clear

2022-02-22 13:11 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +    <Complete></Complete>
<Carousel />
<Complete />

2022-02-22 13:21 UTC, Kushan1994 commented on resources/js/Components/ProjectFrontend/Completed/Complete.vue
> +<script setup>
it is complete project components.  "Components/ProjectFrontend/Completed/Project.vue" That name is OK ?

2022-02-24 02:33 UTC, sureshhemal commented on resources/js/Components/ProjectFrontend/Completed/Complete.vue
> +<script setup>
Lets make `Components/Projects/Completed.vue`

2022-02-24 02:35 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +    <Complete></Complete>
@Kushan1994 change those tags to `<Carousel />` and `<Complete />`

2022-02-24 02:35 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +    <Complete></Complete>
And what is the `<Complete />` ? It doesn't make sence

2022-02-24 10:29 UTC, sureshhemal approved these changes

2022-02-24 10:29 UTC, sureshhemal commented on resources/js/Components/Projects/Complete.vue
> +<script setup>
rename file as `Completed.vue`

2022-02-24 10:29 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +import CompleteProject from "@/Components/Projects/Complete";
completed projects

2022-02-24 10:29 UTC, sureshhemal commented on resources/js/Pages/Frontend/Home.vue
> +    <CompleteProject />
completed porjects.

2022-02-24 10:29 UTC, sureshhemal commented on resources/js/Components/Projects/CompleteItem.vue
> +<script setup></script>
file path is not correct. There is only `project` component inside `Component` folder. This file system hard to understand. Lets move all homepage components to single folder called `Components/Homepage`

So this must be `Components/Homepage/Projects/Completed.vue`

2022-02-24 18:32 UTC, sureshhemal approved these changes

2022-02-24 18:43 UTC, sureshhemal approved these changes

2022-02-24 18:43 UTC, merged