Contact section frontend
websolcr/rn-constructions pull request #40
Opened 2022-02-23 13:03 UTC by Kushan1994

2022-02-25 14:51 UTC, sureshhemal requested changes

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                        <input id="budget-under-25k" name="budget" value="under_25k" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" />
`<Input>` do capital

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                        <input id="budget-25k-50k" name="budget" value="25k-50k" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" />
Capital

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                        <input id="budget-50k-100k" name="budget" value="50k-100k" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" />
Capital

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                        <input id="budget-over-100k" name="budget" value="over_100k" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" />
capital

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                <Button type="submit">Submit</Button>
remove `type` attribute. submit is the default one. Do not need to mention it here

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/Contact.vue
> +import ContactForm from "@/Components/Frontend/Contact/ContactForm";
rename component as Form.vue

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactInfoBg.vue
> +<template>
didn't understand the filename

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactInformation.vue
> +<script setup>
rename as `Information.vue`

2022-02-25 14:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Contact/ContactInformation.vue
> +        <ContactInfoBg />
what is this?

2022-02-25 14:57 UTC, Kushan1994 commented on resources/js/Components/Frontend/Contact/ContactForm.vue
> +                        <input id="budget-under-25k" name="budget" value="under_25k" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" />
eka iwara netho radio dann oni hadala

2022-02-28 03:51 UTC, sureshhemal requested changes

2022-02-28 03:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +        </svg>
make different component

2022-02-28 03:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +        </svg>
make different component.

2022-02-28 03:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +        </svg>
make different component

2022-02-28 03:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Form.vue
> +        <form action="#" method="POST" class="mt-6 grid grid-cols-1 gap-y-3 sm:grid-cols-2 sm:gap-x-2">
there is no need of `<form>` tag. remove this

2022-02-28 03:51 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Information.vue
> +    </div>
unnecessary white spaces

2022-03-02 11:11 UTC, sureshhemal requested changes

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +import Image from "@/Components/SvgImages/VectorPath/Square";
SquareDefault

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +import ImageLgVersion from "@/Components/SvgImages/VectorPath/SquareLg";
ImageLarge

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Background.vue
> +import ImageMobileVersion from "@/Components/SvgImages/VectorPath/SquareSm";
ImageMobile

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Form.vue
> +
blank line

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Form.vue
> +
blank line

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Information.vue
> +
remove blank line

2022-03-02 11:11 UTC, sureshhemal commented on resources/js/Components/Frontend/Homepage/Contact/Information.vue
> +            </dd>
make dynamic

2022-03-04 16:27 UTC, sureshhemal approved these changes

2022-03-04 16:27 UTC, merged